version: 2

sources:
  - name: dbt_demo         # nom du schéma dans Databricks
    database: workspace_1  # nom de la base/catalogue dans Databricks
    tables:
      - name: data_salaries
        description: "Table contenant les données de salaires."
        columns:
          - name: id
            description: "Identifiant unique."
          - name: salary
            description: "Salaire annuel."
